#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/lib/workspace.sh — the ONE file that holds this workspace's specifics.
#
# Generated by /meta-repo-harness:setup and re-generated on bump. Every mechanism script
# (status / doctor / dev / worktree/* / govern/*) sources THIS file for repo
# names, ports, org, and worktree layout. Because all customization lives here,
# the mechanism scripts stay byte-identical across every meta-repo install — so a
# `/meta-repo-harness:setup` bump can refresh them safely without ever clobbering your
# tweaks. Edit THIS file (and the optional hooks at the bottom); leave the
# mechanism scripts alone.
#
# Source, don't execute:  source "<root>/scripts/lib/workspace.sh"
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

# Absolute path of the workspace root (the main checkout). Scripts that live in
# scripts/, scripts/worktree/, scripts/govern/ resolve it relative to themselves;
# this fallback assumes this file sits at <root>/scripts/lib/workspace.sh.
META_ROOT="${META_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

# Workspace name (folder basename) and the package manager the ROOT uses to run
# the cross-cutting scripts. Sub-repos keep their OWN package manager (see
# REPO_CMDS) — ROOT_PM only governs `<pm> run <script>` at the workspace root.
META_NAME="__META_NAME__"           # e.g. aquanode
ROOT_PM="npm"                        # npm | pnpm | yarn | bun

# GitHub org/owner for `gh` operations (push-prs, governor merges, PR lookups).
GITHUB_ORG="__GITHUB_ORG__"          # e.g. Aquanodeio

# Sub-repos, dev commands, and base ports — three INDEX-ALIGNED arrays (parallel,
# not associative). macOS ships bash 3.2, which has no `declare -A`, so we pair by
# position: REPOS[i] ⇄ REPO_CMDS[i] ⇄ REPO_PORTS[i]. Keep all three the same length
# and order. Use the wsp_repo_* helpers below to look up by name.
REPOS=(__REPOS__)                    # e.g. (backend console website)

# Dev command per sub-repo — detected from each sub-repo's lockfile / Makefile.
# Do NOT assume one PM for all: package-lock.json→"npm run dev",
# pnpm-lock.yaml→"pnpm dev", yarn.lock→"yarn dev", bun.lockb→"bun run dev",
# Makefile w/ a run target→"make run", Cargo.toml→"cargo run", go.mod→"go run ./...".
REPO_CMDS=(__REPO_CMDS__)            # e.g. ("npm run dev" "pnpm dev" "make run")

# Base dev port per sub-repo (the port it binds in the MAIN checkout = slot 0).
# Worktree slot k binds base + k*SLOT_PORT_STEP. Use "" for a repo with no HTTP
# server (CLI/lib) — keep the slot so the arrays stay aligned.
REPO_PORTS=(__REPO_PORTS__)          # e.g. (3080 3000 "")
SLOT_PORT_STEP=10                    # port offset per worktree slot

# Where worktrees live: $WORKTREE_BASE/<name>/ (a sibling of the main checkout
# so editor/file-watchers don't index it as a subdir of the workspace).
WORKTREE_BASE="${WORKTREE_BASE:-__WORKTREE_BASE__}"   # e.g. $HOME/code/aquanode.wt

# ── Governor (autonomous ticket loop) ───────────────────────────────────────
# Sub-repos the governor may AUTO-MERGE once CI is green-or-no-checks. Everything
# else is PR-only (the governor opens the PR and stops). Put repos whose CI runs
# POST-merge (e.g. Cloud Build / a deploy pipeline, so PRs show no checks) here;
# keep anything a human must eyeball (frontend behind a billing'd preview) out.
GOVERN_MERGE_REPOS=(__GOVERN_MERGE_REPOS__)          # e.g. (backend)
GOVERN_WORKER_MODEL="${GOVERN_WORKER_MODEL:-opus}"   # model for headless workers

# ── Optional project hooks (create the file to enable; absent = skipped) ─────
# scripts/lib/worktree-bootstrap.sh  <name> <slot> <worktree-path>
#     Per-worktree setup AFTER the trees are laid out: install deps, codegen
#     (prisma generate), point a worktree DB at prod, set a per-slot Redis DB,
#     etc. This is where every project-specific "make the stack runnable in a
#     fresh worktree" step lives. worktree/new.sh calls it if present.
# scripts/lib/session-cleanup.sh
#     Project cleanup run by the SessionEnd hook and worktree/rm.sh BEFORE a
#     worktree is torn down — e.g. close billable test deploys. Best-effort.
# GOVERN_MIGRATE_CMD / GOVERN_VERIFY_CMD  (env, optional)
#     If a resolved ticket carries an ADDITIVE prod migration, the governor runs
#     MIGRATE then VERIFY after merge. Leave unset to disable auto-migration.
export GOVERN_MIGRATE_CMD="${GOVERN_MIGRATE_CMD:-}"
export GOVERN_VERIFY_CMD="${GOVERN_VERIFY_CMD:-}"

# ── Derived helpers (bash 3.2 safe — index lookups, no associative arrays) ───
# Index of <repo> in REPOS, or non-zero exit if absent.
wsp_repo_index() {
  local r="$1" i
  for i in "${!REPOS[@]}"; do [ "${REPOS[$i]}" = "$r" ] && { echo "$i"; return 0; }; done
  return 1
}

# Port for <repo> at worktree <slot> (slot 0 = main checkout). Empty if the repo
# has no base port or isn't known.
wsp_repo_port() {
  local i base
  i=$(wsp_repo_index "$1") || return 0
  base="${REPO_PORTS[$i]:-}"
  [ -n "$base" ] || return 0
  echo $(( base + ${2:-0} * SLOT_PORT_STEP ))
}

# Dev command for <repo> (empty if unknown).
wsp_repo_cmd() {
  local i
  i=$(wsp_repo_index "$1") || return 0
  echo "${REPO_CMDS[$i]:-}"
}

# Comma-joined REPOS (handy for --only defaults and messages).
wsp_repos_csv() { local IFS=,; echo "${REPOS[*]}"; }

# Is <repo> in the governor auto-merge allowlist? (empty-array safe under set -u)
wsp_is_merge_repo() {
  local r="$1" a
  [ "${#GOVERN_MERGE_REPOS[@]}" -eq 0 ] && return 1
  for a in "${GOVERN_MERGE_REPOS[@]}"; do [ "$r" = "$a" ] && return 0; done
  return 1
}

# owner/repo slug for a short repo name — what `gh --repo` wants. The DEFAULT is
# "$GITHUB_ORG/<repo>", which covers every sub-repo that lives under your org.
# OVERRIDE this if a repo lives under a DIFFERENT owner (e.g. a skill-template
# repo on your personal account while sub-repos are org-owned) — add a `case`
# arm returning the cross-owner slug. Keep the default arm intact.
wsp_repo_slug() { # short-repo-name -> owner/repo
  case "$1" in
    # example cross-owner override:
    #   my-templates) printf '%s' "someuser/my-templates" ;;
    *) printf '%s/%s' "$GITHUB_ORG" "$1" ;;
  esac
}

# Local checkout dir for a short repo name. The DEFAULT is "$META_ROOT/<repo>"
# (a sub-folder of the main checkout). OVERRIDE for a repo whose working copy
# lives elsewhere (e.g. the meta-repo itself = $META_ROOT, or a repo cloned
# outside the workspace). Used by merge-pr.sh to delete a lingering local
# ticket-<N> branch after a squash-merge. Keep the default arm intact.
wsp_repo_localdir() { # short-repo-name -> abs path
  case "$1" in
    # example overrides:
    #   harness)   printf '%s' "$META_ROOT" ;;
    #   my-templates) printf '%s' "$HOME/.config/my-templates" ;;
    *) printf '%s/%s' "$META_ROOT" "$1" ;;
  esac
}
