#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/lib/workspace.sh — the ONE file that holds this workspace's specifics.
#
# Generated by /shiploop:setup and re-generated on bump. Every mechanism script
# (status / doctor / dev / worktree/* / govern/*) sources THIS file for repo
# names, ports, org, and worktree layout. Because all customization lives here,
# the mechanism scripts stay byte-identical across every meta-repo install — so a
# `/shiploop:setup` bump can refresh them safely without ever clobbering your
# tweaks. Edit THIS file (and the optional hooks at the bottom); leave the
# mechanism scripts alone.
#
# Source, don't execute:  source "<root>/scripts/lib/workspace.sh"
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

# Absolute path of the workspace root (the main checkout). Scripts that live in
# scripts/, scripts/worktree/, scripts/govern/ resolve it relative to themselves;
# this fallback assumes this file sits at <root>/scripts/lib/workspace.sh.
META_ROOT="${META_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

# Workspace name (folder basename) and the package manager the ROOT uses to run
# the cross-cutting scripts. Sub-repos keep their OWN package manager (see
# REPO_CMDS) — ROOT_PM only governs `<pm> run <script>` at the workspace root.
META_NAME="__META_NAME__"           # e.g. aquanode
ROOT_PM="npm"                        # npm | pnpm | yarn | bun

# GitHub org/owner for `gh` operations (push-prs, governor merges, PR lookups).
GITHUB_ORG="__GITHUB_ORG__"          # e.g. Aquanodeio

# Sub-repos, dev commands, and base ports — three INDEX-ALIGNED arrays (parallel,
# not associative). macOS ships bash 3.2, which has no `declare -A`, so we pair by
# position: REPOS[i] ⇄ REPO_CMDS[i] ⇄ REPO_PORTS[i]. Keep all three the same length
# and order. Use the wsp_repo_* helpers below to look up by name.
REPOS=(__REPOS__)                    # e.g. (backend console website)

# Dev command per sub-repo — detected from each sub-repo's lockfile / Makefile.
# Do NOT assume one PM for all: package-lock.json→"npm run dev",
# pnpm-lock.yaml→"pnpm dev", yarn.lock→"yarn dev", bun.lockb→"bun run dev",
# Makefile w/ a run target→"make run", Cargo.toml→"cargo run", go.mod→"go run ./...".
REPO_CMDS=(__REPO_CMDS__)            # e.g. ("npm run dev" "pnpm dev" "make run")

# Base dev port per sub-repo (the port it binds in the MAIN checkout = slot 0).
# Worktree slot k binds base + k*SLOT_PORT_STEP. Use "" for a repo with no HTTP
# server (CLI/lib) — keep the slot so the arrays stay aligned.
REPO_PORTS=(__REPO_PORTS__)          # e.g. (3080 3000 "")
SLOT_PORT_STEP=10                    # port offset per worktree slot

# Where worktrees live: $WORKTREE_BASE/<name>/ (a sibling of the main checkout
# so editor/file-watchers don't index it as a subdir of the workspace).
WORKTREE_BASE="${WORKTREE_BASE:-__WORKTREE_BASE__}"   # e.g. $HOME/code/aquanode.wt

# ── Governor (autonomous ticket loop) ───────────────────────────────────────
# Repos the governor may AUTO-MERGE once CI is green-or-no-checks. Everything
# else is PR-only (the governor opens the PR and stops). Put repos whose CI runs
# POST-merge (e.g. Cloud Build / a deploy pipeline, so PRs show no checks) here;
# keep anything a human must eyeball (frontend behind a billing'd preview) out.
# SPACE-SEPARATED, and it defines the governor's whole PR/merge UNIVERSE: the
# PR-search + merge loops iterate THIS list (plus the derived frontend repos), NOT
# $REPOS — so it may include a cross-owner repo that is NOT a sub-repo in $REPOS
# (e.g. the meta-repo itself, or a skill-template repo on another owner). Give any
# such repo a wsp_repo_slug / wsp_repo_localdir override below.
GOVERN_MERGE_REPOS="${GOVERN_MERGE_REPOS:-__GOVERN_MERGE_REPOS__}"   # space-separated; e.g. "backend api"
GOVERN_WORKER_MODEL="${GOVERN_WORKER_MODEL:-opus}"   # model for headless workers

# ── Trust ladder (GOVERN_AUTONOMY) ───────────────────────────────────────────
# How much the governor is allowed to do on its own. Flip ONE knob as trust builds — the graduation
# is observe → pr-only → auto (see commands/govern.md + governor/README.md):
#   observe   Workers do the work, commit, push their `ticket-<N>` branch, and open a DRAFT PR — but
#             the governor NEVER merges. Everything is VISIBLE (a PR to read) yet INERT. The safest
#             first setting: watch what the harness produces without a single line landing on `main`.
#   pr-only   Workers open NORMAL (ready-for-review) PRs; the governor STILL never auto-merges — a
#             human reviews + clicks merge. This is the default for a NEW scaffold: you get the full
#             ship pipeline minus the final merge, so nothing lands until you say so.
#   auto      Full autonomy — the governor auto-merges every allowlisted-repo PR on green-or-no-checks
#             CI (frontend stays PR-only regardless). Flip to this once you trust the loop.
# BACKWARD COMPAT: a workspace.sh that predates this knob has NO GOVERN_AUTONOMY line at all → the
# governor treats an absent/empty value as `auto` (today's behavior is preserved for existing installs).
# A NEW scaffold seeds `pr-only` right here, so first-time adopters start one rung down the ladder.
export GOVERN_AUTONOMY="${GOVERN_AUTONOMY:-pr-only}"   # observe | pr-only | auto

# Sub-repos that are LOCAL-FIRST — they run on each user's machine, NOT a deployed server, so they
# have NO central prod DB. A schema change ships AS CODE (a migration that self-applies on the user's
# local DB open), so an ADDITIVE migration needs NO manual prod apply — the governor must open the PR
# normally, never park it "apply to prod manually". DESTRUCTIVE migrations still escalate. Empty by
# default (feature is OFF) — set to a space-separated repo list to opt in (e.g. "cli-tool desktop-app").
GOVERN_LOCAL_FIRST_REPOS="${GOVERN_LOCAL_FIRST_REPOS:-}"

# ── Externalization lane (OPT-IN, OFF by default) ────────────────────────────
# Each governor run files every OPEN Low-severity ticket whose Where targets the OSS sub-repo as a
# public GitHub Issue on GOVERN_EXTERNALIZE_REPO, then removes it from the local queue — seeding
# "good first issue" work for outside contributors. The whole lane no-ops unless BOTH
# GOVERN_EXTERNALIZE_REPO and GOVERN_EXTERNALIZE_SUBREPO are set, so this is a pure opt-in.
#   GOVERN_EXTERNALIZE_LANE     1=on (default when the vars below are set) / 0=off.
#   GOVERN_EXTERNALIZE_REPO     owner/repo the issues are filed on (the public OSS sub-repo).
#   GOVERN_EXTERNALIZE_SUBREPO  the sub-repo NAME matched in the **Where:** line. Sibling repos whose
#                               name merely CONTAINS it (e.g. `myproject-website` ⊃ `myproject`) are excluded.
#   GOVERN_EXTERNALIZE_LABELS   manual label override applied verbatim ("" = AUTO-DECIDE: the lane
#                               fetches the repo's existing labels and picks from them per issue).
# OPERATOR NOTE: for labels to actually APPLY, the gh account the governor is authed as needs
# ≥ Triage on GOVERN_EXTERNALIZE_REPO. A pull-only account still files the issue (URL is returned) but
# GitHub rejects the label step (addLabelsToLabelable) — the lane emits a "filed but LABELS REJECTED"
# WARN instead of a silent success in that case, but the labels won't stick until Triage is granted.
export GOVERN_EXTERNALIZE_LANE="${GOVERN_EXTERNALIZE_LANE:-1}"
export GOVERN_EXTERNALIZE_REPO="${GOVERN_EXTERNALIZE_REPO:-}"
export GOVERN_EXTERNALIZE_SUBREPO="${GOVERN_EXTERNALIZE_SUBREPO:-}"
export GOVERN_EXTERNALIZE_LABELS="${GOVERN_EXTERNALIZE_LABELS:-}"

# ── Optional harness → template sync channel (OPT-IN, OFF by default) ────────
# When set, `sync-templates.sh` + `sync-port.sh` become live: they detect drift
# between the mirrored files in this workspace and the shiploop
# templates and — for sync-port — spawn a headless porter, validate the port,
# open a PR against the upstream repo, merge it green-or-no-checks, and advance
# the local marker. This is the *contribution* channel that lets a live
# workspace push its own hardening back into the templates for other adopters.
# BOTH knobs empty (default) → the whole mechanism is inert.
#
#   GOVERN_UPSTREAM_HARNESS_REPO — short repo name of your fork OR the canonical
#     "shiploop" repo. sync-port passes it to merge-pr.sh + resolves it
#     to owner/repo via wsp_repo_slug. If your fork lives under a different
#     GitHub owner than $GITHUB_ORG, add a wsp_repo_slug case arm below
#     mapping the short name to the cross-owner slug.
#     Example: GOVERN_UPSTREAM_HARNESS_REPO="shiploop"
#              wsp_repo_slug() { case "$1" in shiploop) printf 'anshss/shiploop';; ...
#
#   GOVERN_UPSTREAM_HARNESS_DIR — local working dir where you keep a clone of
#     your fork of shiploop. sync-templates uses it as the templates
#     tree to diff against; sync-port cuts its port branch there. Point this at
#     wherever you keep the checkout — the default wsp_repo_localdir places
#     every repo under $META_ROOT which almost never matches for a skill fork.
#     Example: GOVERN_UPSTREAM_HARNESS_DIR="$HOME/code/shiploop"
#
# Also useful:
#   Add "$GOVERN_UPSTREAM_HARNESS_REPO" to GOVERN_MERGE_REPOS above so
#   sync-port can auto-merge the PR it opens against the upstream repo.
export GOVERN_UPSTREAM_HARNESS_REPO="${GOVERN_UPSTREAM_HARNESS_REPO:-}"
export GOVERN_UPSTREAM_HARNESS_DIR="${GOVERN_UPSTREAM_HARNESS_DIR:-}"

# ── Optional pre-commit lint-fix hook (OPT-IN, OFF by default) ───────────────
# When set, the workspace's per-sub-repo pre-commit hook (.githooks/pre-commit, propagated by
# lib/githooks.sh:install_subrepo_pre_commit_hook) runs this command inside the sub-repo BEFORE
# every commit, then `git add -u`'s the touched files. Any command that fixes in place idempotently
# will do — e.g. "pnpm lint --fix", "prettier --write .", "gofmt -w .", "cargo fmt". Empty (default)
# → the pre-commit hook is a no-op. Failures are SOFT: the commit proceeds either way, because a
# broken linter must never block the operator (or the governor) mid-commit — CI catches real
# regressions. Sub-repos that already have a pre-commit hook (husky, lefthook, hand-rolled) are
# left untouched; the workspace hook is only installed where the slot is empty or previously ours.
export WSP_LINT_FIX_CMD="${WSP_LINT_FIX_CMD:-}"

# ── Viral PR footer (ON by default) ──────────────────────────────────────────
# Every PR a governor worker opens ends its body with one attribution line:
#   PR shipped by [shiploop](https://github.com/anshss/shiploop)
# It marks work the harness shipped so an adopter's collaborators discover shiploop from the PR. ON by
# default; set to `off` to suppress it (the worker then closes the body with the plain Co-Authored-By
# trailer only). Any value other than `off` (or an absent knob, for a workspace.sh predating it) = ON.
export WSP_PR_FOOTER="${WSP_PR_FOOTER:-on}"   # on | off

# ── Optional project hooks (create the file to enable; absent = skipped) ─────
# scripts/lib/worktree-bootstrap.sh  <name> <slot> <worktree-path>
#     Per-worktree setup AFTER the trees are laid out: install deps, codegen
#     (prisma generate), point a worktree DB at prod, set a per-slot Redis DB,
#     etc. This is where every project-specific "make the stack runnable in a
#     fresh worktree" step lives. worktree/new.sh calls it if present.
# scripts/lib/session-cleanup.sh
#     Project cleanup run by the SessionEnd hook and worktree/rm.sh BEFORE a
#     worktree is torn down — e.g. close billable test deploys. Best-effort.
# GOVERN_MIGRATE_CMD / GOVERN_VERIFY_CMD  (env, optional)
#     If a resolved ticket carries an ADDITIVE prod migration, the governor runs
#     MIGRATE then VERIFY after merge. Leave unset to disable auto-migration.
export GOVERN_MIGRATE_CMD="${GOVERN_MIGRATE_CMD:-}"
export GOVERN_VERIFY_CMD="${GOVERN_VERIFY_CMD:-}"

# ── Derived helpers (bash 3.2 safe — index lookups, no associative arrays) ───
# Index of <repo> in REPOS, or non-zero exit if absent.
wsp_repo_index() {
  local r="$1" i
  for i in "${!REPOS[@]}"; do [ "${REPOS[$i]}" = "$r" ] && { echo "$i"; return 0; }; done
  return 1
}

# Port for <repo> at worktree <slot> (slot 0 = main checkout). Empty if the repo
# has no base port or isn't known.
wsp_repo_port() {
  local i base
  i=$(wsp_repo_index "$1") || return 0
  base="${REPO_PORTS[$i]:-}"
  [ -n "$base" ] || return 0
  echo $(( base + ${2:-0} * SLOT_PORT_STEP ))
}

# Dev command for <repo> (empty if unknown).
wsp_repo_cmd() {
  local i
  i=$(wsp_repo_index "$1") || return 0
  echo "${REPO_CMDS[$i]:-}"
}

# Comma-joined REPOS (handy for --only defaults and messages).
wsp_repos_csv() { local IFS=,; echo "${REPOS[*]}"; }

# Is <repo> in the governor auto-merge allowlist? (word-split over the space
# list; a blank GOVERN_MERGE_REPOS just iterates nothing — empty-safe under set -u)
wsp_is_merge_repo() {
  local r="$1" a
  for a in $GOVERN_MERGE_REPOS; do [ "$r" = "$a" ] && return 0; done
  return 1
}

# Is <repo> local-first? (no deployed prod DB → additive migrations self-apply as code.) Empty list =
# feature off = always returns 1 (nothing is local-first), which the govern helper below defaults to.
wsp_is_local_first_repo() {
  local r="$1" a
  for a in $GOVERN_LOCAL_FIRST_REPOS; do [ "$r" = "$a" ] && return 0; done
  return 1
}

# owner/repo slug for a short repo name — what `gh --repo` wants. The DEFAULT is
# "$GITHUB_ORG/<repo>", which covers every sub-repo that lives under your org.
# OVERRIDE this if a repo lives under a DIFFERENT owner (e.g. a skill-template
# repo on your personal account while sub-repos are org-owned) — add a `case`
# arm returning the cross-owner slug. Keep the default arm intact.
wsp_repo_slug() { # short-repo-name -> owner/repo
  case "$1" in
    # example cross-owner override:
    #   my-templates) printf '%s' "someuser/my-templates" ;;
    *) printf '%s/%s' "$GITHUB_ORG" "$1" ;;
  esac
}

# Local checkout dir for a short repo name. The DEFAULT is "$META_ROOT/<repo>"
# (a sub-folder of the main checkout). OVERRIDE for a repo whose working copy
# lives elsewhere (e.g. the meta-repo itself = $META_ROOT, or a repo cloned
# outside the workspace). Used by merge-pr.sh to delete a lingering local
# ticket-<N> branch after a squash-merge. Keep the default arm intact.
wsp_repo_localdir() { # short-repo-name -> abs path
  case "$1" in
    # example overrides:
    #   harness)   printf '%s' "$META_ROOT" ;;
    #   my-templates) printf '%s' "$HOME/.config/my-templates" ;;
    *) printf '%s/%s' "$META_ROOT" "$1" ;;
  esac
}
